apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello-world
  name: hello-world
  namespace: hello-world
spec:
  selector:
    matchLabels:
      app: hello-world
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - image: service-helloworld
        name: service-helloworld
        resources: {}
        imagePullPolicy: Never
        ports:
          - name: http-port
            containerPort: 5000
            protocol: TCP